# Generated by Django 5.1.4 on 2024-12-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resposta',
            name='resposta_unica',
        ),
        migrations.AddField(
            model_name='aluno',
            name='total_pontos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='dificuldade',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='facil', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='resposta',
            constraint=models.UniqueConstraint(fields=('aluno', 'pergunta'), name='resposta_unica', violation_error_message='Cada aluno pode responder a cada pergunta apenas uma vez.'),
        ),
    ]
