# Generated by Django 5.1.4 on 2024-12-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_resposta_resposta_unica_aluno_total_pontos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='dificuldade',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil'), ('especialista', 'Especialista')], default='facil', max_length=12),
        ),
    ]
