# Generated by Django 5.1.4 on 2024-12-29 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_pergunta_dificuldade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('finalizada', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='resposta',
            name='resposta_unica',
        ),
        migrations.AddField(
            model_name='aluno',
            name='pontuacao_maxima',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alternativas',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='partida',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.aluno'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.partida'),
        ),
        migrations.AddConstraint(
            model_name='resposta',
            constraint=models.UniqueConstraint(fields=('partida', 'pergunta'), name='resposta_unica_partida'),
        ),
    ]
