# Generated by Django 5.1.4 on 2024-12-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_partida_remove_resposta_resposta_unica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.partida'),
        ),
    ]
